extends: "airbnb/base"
ecmaFeatures:
  modules: false
rules:
  ###################
  # Possible Errors #
  ###################
  comma-dangle:
    - 2
    - "never"

  ##################
  # Best Practices #
  ##################
  dot-location:
    - 2
    - "property"
  no-param-reassign: 0

  ################
  # Strict Mode #
  ###############
  strict:
    - 2
    - "global"

  #############
  # Variables #
  #############
  no-use-before-define: 0

  ####################
  # Stylistic Issues #
  ####################
  max-len:
    - 2
    - 100
    - 2
    -
      ignoreUrls: true
      ignoreComments: true
  new-cap:
    - 2
    -
      capIsNew: false
  semi:
    - 2
    - "never"

  ################
  # ECMAScript 6 #
  ################
  object-shorthand: 0
